name: ci/cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Build application (copy files to dist/)
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the build job runs first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the build job runs first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Build application (copy src/ to dist/)
        run: npm run build

      - name: Archive dist/ into a tarball
        run: |
          tar -czf dist.tar.gz dist/  # Compress dist/ into a .tar.gz file
          echo "dist/ folder archived into dist.tar.gz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.gz  # Upload the tarball as part of the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}